name: Test SSH Connection

on:
  workflow_dispatch: # Permet de lancer le workflow manuellement

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connexion r√©ussie !"
            whoami
            pwd